version: '3.8'

services:
  mariadb:
    image: mariadb:10.11
    container_name: wprog2_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: guestbook_db
      MYSQL_USER: guestbook_user
      MYSQL_PASSWORD: guestbook_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: